#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-only
# Vanadium-E copy of ../../generate-release: signs with the Vanadium-E key (alias vanadium-e).
[[ $# -ge 1 ]] || exit 1

set -o errexit -o nounset -o pipefail

KEYSTORE=${VANADIUM_E_KEYSTORE:-$HOME/.vanadium-e/vanadium-e.keystore}
APKSIGNER=$PWD/third_party/android_sdk/public/build-tools/37.0.0/apksigner
readonly APPS=(
    TrichromeChrome
    TrichromeLibrary
    TrichromeWebView
    VanadiumConfig
)

read -p "Enter keystore passphrase: " -s keystore_pass
echo

for d in "$@"; do
    cd "$d/Default/apks"

    rm -rf release
    mkdir release
    cd release

    for app in ${APPS[@]}; do
        input=$(echo -n ../${app}*.apk)
        [[ ! -f $input ]] && echo "missing ${app}" && continue
        $APKSIGNER sign --ks $KEYSTORE --ks-pass file:/dev/stdin --ks-key-alias vanadium-e --in $input --out $app.apk <<< $keystore_pass || true
    done

    cd ../../../..
done
